### ISSUE TITLE
Train stations marked as "way" don't appear in the final PNG

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#6]
The `stops` query looks for `node[railway=station]({{bbox}});` but some train stations ([like Howard](https://www.openstreetmap.org/way/384912974)) in Chicago are not tagged as nodes. They are tagged as `building`, which is an area. 

I see two possible fixes:
1. Change the tagging on OpenStreetMap so that these stations have a node instead of a way.
2. Change the query to include way objects. Question: Would the stylesheet place a circle in the centroid of this building?

I think 2 is preferable because there's probably a good reason that someone mapped the stations like that. Hat tip Justin H. for spotting this anomaly.

`stops` style, for reference:

```
.stops {
    r: 7.7;
    fill: white;
    stroke: #323589;
    stroke-width: 2.00px;
}
```

**Comment by stevevance** [comment]
I added `way[railway=station]({{bbox}});` to the `stops` query but this had no effect in adding the stations. 
It looks like there's a function to get the "center" of an area, but it's not guaranteed to be inside the polygon. That might be okay. 

Here's some relevant code I found on the [OSM wiki](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Actions):

```
[bbox:{{bbox}}];
area[boundary=postal_code][postal_code="65343"];
rel(pivot);out center;>;out;
```

**Comment by fitnr** [comment]
I closed the other issue because it's another facet of the same problem: the stop data in OSM doesn't match your database.

If you want to keep each point as a shape, the simplest solution would probably be to download the `POINT` from pgsql and draw it. Right now we don't download the point, we just use it to draw a circle.

Editing OSM is also a Good Thing. It should be consistent within the CTA.

If we're going to draw some kind of station polygon, I would suggest the <strike>platform, although that might look odd for subway stations</strike> (edit: platform is a line element). Alternately, putting points on every entrance might work. They could even be colored according to the CTA line name, with a little creative CSS.

> Would the stylesheet place a circle in the centroid of this building?

No, that would be beyond the capabilities of CSS in SVGs.

**Comment by stevevance** [comment]
For now I'm going to edit OSM. I would prefer that there isn't 1% of CTA or Metra stations tagged differently.
